// <auto-generated />
using API_Sistema_Farmacia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Sistema_Farmacia.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API_Sistema_Farmacia.Models.FilmesModels", b =>
                {
                    b.Property<int>("cod_filme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("avaliacao")
                        .HasColumnType("float");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("duracao")
                        .HasColumnType("int");

                    b.Property<string>("genero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome_filme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sinopse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("url_imagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("url_video")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("cod_filme");

                    b.ToTable("filmes");
                });
#pragma warning restore 612, 618
        }
    }
}
